version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=tagger-user
      - POSTGRES_PASSWORD=tagger-pwd
      - POSTGRES_DB=tagger-db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:6.13
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    links:
      - postgres:postgres
    depends_on:
      - postgres
    volumes:
      - ./dump:/dump
    ports:
      - 8081:80
    networks:
      - default

networks:
  default:
    driver: bridge
