CREATE TABLE tag
( id UUID PRIMARY KEY
, name TEXT NOT NULL
)

CREATE TABLE content
( id UUID PRIMARY KEY
, content TEXT NOT NULL
)

CREATE TABLE contents_tags
( content_id UUID REFERENCES content (id) ON DELETE CASCADE ON UPDATE CASCADE
, tag_id     UUID REFERENCES tag     (id) ON DELETE CASCADE ON UPDATE CASCADE
)
