resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/1.yaml

packages:
  - .

extra-deps:
  - co-log-core-0.3.1.0
  - postgresql-error-codes-1.0.1
  - tomland-1.3.3.1
  - validation-selective-0.1.0.1
  - git: git@github.com:haskell-servant/servant.git
    commit: d05da71f09be08131d29a2c17f613a4bd71faea2
    subdirs:
      - servant-auth/servant-auth-server

allow-newer: true
